# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matt Couchman | Front end web developer | Birmingham
email: 
description: Matt Couchman | Front end web developer based in Birmingham, West Midlands. Specialising in CSS, Javascript, accessibility and performance.
baseurl: "" # the subpath of your site, e.g. /blog
excerpt_separator: <!--excerpt-->
url: "http://www.mattcouchman.co.uk" # the base hostname & protocol for your site
twitter_username: mattcouchman
github_username:  mattcouchman

# Build settings
markdown: kramdown
